# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190826_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='changed_date',
            field=models.DateField(verbose_name='Date of Change'),
        ),
    ]
