# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190827_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='changed_date',
            field=models.DateField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
