# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190827_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='Creation Date'),
        ),
    ]
